//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int Id { get; set; }
        public System.DateTime RandevuTarih { get; set; }
        public string RandevuSaat { get; set; }
        public int BransId { get; set; }
        public int DoktorId { get; set; }
        public int HastaId { get; set; }
        public string HastaSikayet { get; set; }
    
        public virtual Brans Brans { get; set; }
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
